version: '2.1'
services:
  mysql:
    image: mysql/mysql-server:5.7
    restart: always
    hostname: mysql
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./tmp/mysql:/var/lib/mysql

  redis:
    # docker run --rm -p 6379:6379 -e  --name merch_redis bitnami/redis:latest
    image: bitnami/redis:latest
    hostname: redis
    expose:
      - 6379
    ports:
      - 6379:6379
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'

  api:
    image: alerdenisov/main-explorer:latest
    depends_on:
      - mysql
      - redis
    volumes:
      - ./src:/usr/src/app/src
    build:
      context: .
    environment:
      PORT: 4000
      DATABASE_HOST: mysql
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      REDIS_URL: redis://redis:6379
    ports:
      - 4000:4000
    command: /bin/sh dev-run.sh api

  exporter:
    image: alerdenisov/main-explorer:latest
    depends_on:
      - mysql
      - redis
    volumes:
      - ./src:/usr/src/app/src
    build:
      context: .
    environment:
      PORT: 4000
      DATABASE_HOST: mysql
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      REDIS_URL: redis://redis:6379
    command: /bin/sh dev-run.sh exporter
